-- MySQL Script generated by MySQL Workbench
-- 10/31/14 22:53:22
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema csc301project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csc301project` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `csc301project` ;

-- -----------------------------------------------------
-- Table `csc301project`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc301project`.`course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc301project`.`lecture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc301project`.`lecture` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `course_id` INT NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_lecture_course_idx` (`course_id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  CONSTRAINT `fk_lecture_course`
    FOREIGN KEY (`course_id`)
    REFERENCES `csc301project`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc301project`.`assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc301project`.`assignment` (
  `id` INT NOT NULL,
  `lecture_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deadline` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `lecture_id`),
  INDEX `fk_assignment_lecture1_idx` (`lecture_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_assignment_lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `csc301project`.`lecture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csc301project`.`lecture_time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csc301project`.`lecture_time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lecture_id` INT NOT NULL,
  `dow` INT NULL,
  `start` TIME NULL,
  `end` TIME NULL,
  PRIMARY KEY (`id`, `lecture_id`),
  INDEX `fk_lecture_time_lecture1_idx` (`lecture_id` ASC),
  CONSTRAINT `fk_lecture_time_lecture1`
    FOREIGN KEY (`lecture_id`)
    REFERENCES `csc301project`.`lecture` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
